[tools]
lua = "5.1"
rust = "stable"
"cargo:tre-command" = "latest"
"cargo:cargo-cache" = "latest"
eza = "latest"
fzf = "latest"
ghq = "latest"
gh = "latest"
lsd = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"
usage = "latest"
