[tools]
lua = "5.1"
rust = "stable"
"cargo:tre-command" = "latest"
"cargo:cargo-cache" = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
gh = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
"npm:neovim" = "latest"
ripgrep = "latest"
"tree-sitter" = "latest"
starship = "latest"
yarn = "latest"
usage = "latest"
zoxide = "latest"
